# 이것은 작업을 시작하는 데 도움이 되는 기본 워크플로우입니다

이름: CI

# 워크플로우 실행 시기 제어
위에:
  # 푸시 또는 풀 요청 이벤트에서 워크플로우를 트리거하지만 "메인" 브랜치에 대해서만 실행합니다
 푸시:
 나뭇가지: [ "메인" ]
 pull_request:
 나뭇가지: [ "메인" ]

  # 작업 탭에서 이 워크플로를 수동으로 실행할 수 있습니다
 워크플로우_dispatch:

# 워크플로우 실행은 순차적으로 또는 병렬로 실행할 수 있는 하나 이상의 작업으로 구성됩니다
직업:
  # 이 워크플로우에는 "빌드"라는 단일 작업이 포함되어 있습니다
 빌드:
    # 작업이 실행될 러너 유형
 실행 중: 우분투-latest

    # 단계는 작업의 일부로 실행될 일련의 작업을 나타냅니다
 단계:
      # $Github_WORKspace에서 저장소를 체크아웃하면 작업에서 액세스할 수 있습니다
 - 용도: actions/checkout@v4

      # 러너 쉘을 사용하여 단일 명령어를 실행합니다
 - 이름: 한 줄 스크립트 실행
 달려라: 메아리 안녕, 세상이여!

      # 러너 셸을 사용하여 명령어 세트를 실행합니다
 - 이름: 다중 줄 스크립트 실행
 달려.: |
 에코 빌드를 위해 다른 작업을 추가합니다,
 에코 테스트 및 프로젝트 배포.
